*** Variables ***
# TODO: Add the following variables:
# ${BASE_BACKEND_URL}   - set to http://127.0.0.1:8000
# ${BASE_FRONTEND_URL}  - set to http://127.0.0.1:3000
# ${DEFAULT_PET_ID}     - set to 1
# ${DEFAULT_PET_NAME}   - set to Doggie
# ${DEFAULT_ADMIN_USERNAME} - set to admin
# ${DEFAULT_ADMIN_PASSWORD} - set to admin
# ${token}              - set to ${EMPTY}
# ${HEADLESS}           - set to False
# ${BROWSER}            - set to chromium
